# Generated by Django 4.2.3 on 2023-08-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
