# Generated by Django 4.2.3 on 2023-08-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_alter_customer_age_alter_customer_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='DateCreated',
        ),
    ]
