# Generated by Django 4.2.3 on 2023-08-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_remove_customer_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='DateCreated',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
