# Generated by Django 4.2.3 on 2023-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_alter_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Price', models.FloatField(null=True)),
                ('Category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
