# Generated by Django 4.2.3 on 2023-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='ap.tag'),
        ),
    ]
