# Generated by Django 4.2.3 on 2023-08-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
    ]
